/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IOffsets = t.iface([], {
  "meetingHud": t.array("number"),
  "meetingHudCachePtr": t.array("number"),
  "meetingHudState": t.array("number"),
  "exileControllerCachePtr": t.array("number"),
  "gameState": t.array("number"),
  "allPlayersPtr": t.array("number"),
  "allPlayers": t.array("number"),
  "playerCount": t.array("number"),
  "playerAddrPtr": "number",
  "exiledPlayerId": t.array("number"),
  "localPlayerId": t.array("number"),
  "gameCode": t.array("number"),
  "ship": t.array("number"),
  "map": t.array("number"),
  "allDoorsPtr": t.array("number"),
  "plainDoorIsOpen": "number",
  "systemsPtr": t.array("number"),
  "commsSystemType": "number",
  "hudOverrideSystemDefIndex": "number",
  "hudOverrideSystemIsActive": t.array("number"),
  "hqHudSystemDefIndex": "number",
  "hqHudSystemCompletedCount": t.array("number"),
  "deconSystemType": "number",
  "manualDoorDefIndex": "number",
  "upperManualDoor": "number",
  "lowerManualDoor": "number",
  "manualDoorIsOpen": "number",
  "minigame": t.array("number"),
  "minigameClosingState": t.array("number"),
  "surveillanceDefIndex": "number",
  "polusSurveillanceDefIndex": "number",
  "polusSurveillanceCurrentCamera": t.array("number"),
  "player": t.iface([], {
    "localX": t.array("number"),
    "localY": t.array("number"),
    "remoteX": t.array("number"),
    "remoteY": t.array("number"),
    "bufferLength": "number",
    "offsets": t.array("number"),
    "inVent": t.array("number"),
    "struct": t.array(t.iface([], {
      "type": "string",
      "skip": t.opt("number"),
      "name": "string",
    })),
  }),
});

const exportedTypeSuite: t.ITypeSuite = {
  IOffsets,
};
export default exportedTypeSuite;
